# Pandas - Panel Data
- Pandas is built over Numpy
- DataFrame is pretty much like a spreadsheet
- Series is a one-dimensional labelled array capable of holding data of any type(int, float, string etc.)

In [3]:
# Import necessary packages
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [4]:
s_data= Series([2,3,4.0,5,'6']) 
s_data

0    2
1    3
2    4
3    5
4    6
dtype: object

# Selecting and Retrieving

In [5]:
s_data[4]    # Retrieving data as per index

'6'

In [6]:
s_data= Series([2,3,4.0,5],index=['row1','row2','row3','row4'])
s_data     # Auto-typecasted into a float

row1    2.0
row2    3.0
row3    4.0
row4    5.0
dtype: float64

In [7]:
s_data['row2'] # Selecting by a label

3.0

In [8]:
series_data2=Series([34,23,20])
series_data2

0    34
1    23
2    20
dtype: int64

In [9]:
series_data2[2]

20

In [11]:
# Row label assignment with index 
series_data2.index=['row1','row2','row3']
series_data2

row1    34
row2    23
row3    20
dtype: int64

In [12]:
# Label assignment during initiation
series1=Series([2,3,4,5],index=['row1','row2','row3','row4'])
series1

row1    2
row2    3
row3    4
row4    5
dtype: int64

In [15]:
# Retrieve multiple values with label as reference
series2=Series(np.arange(8),index=['row1','row2','row3','row4','row5','row6','row7','row8'])
series2[['row2','row5','row1']]

row2    1
row5    4
row1    0
dtype: int32

In [16]:
series2

row1    0
row2    1
row3    2
row4    3
row5    4
row6    5
row7    6
row8    7
dtype: int32

In [18]:
# Retrieve with index through slicing
series2[0:4]

row1    0
row2    1
row3    2
row4    3
dtype: int32

In [20]:
# Retrieve records by label with slicing
series2['row2':'row4']

row2    1
row3    2
row4    3
dtype: int32

# DataFrame

In [26]:
data1=DataFrame([[2,3,4,5],[8,2,4,2],[12,39,9,3]])
data1

    0   1  2  3
0   2   3  4  5
1   8   2  4  2
2  12  39  9  3

In [28]:
# Assign Labels to the columns
data1.columns=['Col1','Col2','Col3','Col4']
# Assign Labels to the rows
data1.index=['Row1','Row2','Row3']
data1

      Col1  Col2  Col3  Col4
Row1     2     3     4     5
Row2     8     2     4     2
Row3    12    39     9     3

In [34]:
# DataFrame from random numbers generated through numpy
df1=DataFrame(np.floor(np.random.rand(36).reshape(6,6)*100))
df1

      0     1     2     3     4     5
0  85.0  14.0  27.0  25.0  71.0  57.0
1  86.0  27.0  29.0  36.0   3.0   6.0
2  43.0  23.0  44.0  39.0  82.0  41.0
3  17.0  58.0  71.0  32.0  48.0  80.0
4   8.0  41.0  32.0  68.0  26.0  92.0
5  34.0  99.0  55.0  10.0  77.0  21.0

In [38]:
pwd

'C:\\Users\\DELL\\ipython notebook'

In [44]:
# Import Data to DataFrame from CSV
cars=pd.read_csv("mtcars.csv")
cars.head()

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1

In [42]:
cars.tail()

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.5,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.5,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.6,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.6,1,1,4,2

In [46]:
cars.shape

(32, 12)

In [48]:
cars.columns

Index(['car_model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [49]:
cars.index

RangeIndex(start=0, stop=32, step=1)

In [50]:
# Statistical Data Analysis 
cars.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000
mean,19.875000,6.187500,227.925000,145.781250,3.553125,3.200375,17.821563,0.468750,0.437500,3.656250,2.718750
std,5.989184,1.712148,121.708557,67.540542,0.566628,0.992515,1.606035,0.507007,0.504016,0.745281,1.689328
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.000000
25%,15.425000,4.000000,120.250000,103.000000,3.070000,2.428750,16.892500,0.000000,0.000000,3.000000,1.000000
50%,18.650000,6.000000,225.000000,118.000000,3.660000,3.437500,17.900000,0.000000,0.000000,3.500000,2.000000
75%,21.825000,8.000000,307.500000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.000000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,20.220000,1.000000,1.000000,5.000000,8.000000

# Data Slicing

In [52]:
# Retrieve data with index using iloc
cars.iloc[3:10,2:6]  # Rows(before :) and columns(after :)

   cyl   disp   hp  drat
3    6  258.0  110  3.08
4    4  108.0   93  3.85
5    6  225.0  105  2.76
6    8  360.0  245  3.21
7    6  225.0  105  2.76
8    6  225.0  105  2.76
9    6  167.6  123  3.92

In [53]:
# Slicing with loc
cars.loc[2:6,'mpg':'hp']

    mpg  cyl   disp   hp
2  22.8    4  108.0   93
3  21.4    6  258.0  110
4  22.8    4  108.0   93
5  18.1    6  225.0  105
6  14.3    8  360.0  245

In [54]:
# Retrieve multiple columns
cars.loc[2:6,['cyl','drat','wt']]

   cyl  drat     wt
2    4  3.85  2.320
3    6  3.08  3.215
4    4  3.85  2.320
5    6  2.76  3.460
6    8  3.21  3.570

In [55]:
cars.loc[2:6,:'wt']

        car_model   mpg  cyl   disp   hp  drat     wt
2      Datsun 710  22.8    4  108.0   93  3.85  2.320
3  Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215
4      Datsun 710  22.8    4  108.0   93  3.85  2.320
5         Valiant  18.1    6  225.0  105  2.76  3.460
6      Duster 360  14.3    8  360.0  245  3.21  3.570

In [56]:
cars.loc[2:6,'cyl':]

   cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
2    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4    4  108.0   93  3.85  2.320  18.61   1   1     4     1
5    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6    8  360.0  245  3.21  3.570  15.84   0   0     3     4

# Filtering

In [57]:
cars.head()

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1

In [60]:
auto_cars=cars[(cars.am==1) & (cars.hp<100)] # scalar filtering
auto_cars

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
4,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2

# Q1: Cars with mileage >20 and automatic
# Q2: Cars with mileage >30 both automatic and manual
# Q3: Create a DataFrame with 10 rows and 5 columns and export it to excel and also name the columns

In [63]:
cars1=cars[(cars.am==1)&(cars.mpg>20)]
cars1

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
4,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [72]:
cars2=cars[(cars.mpg>30)]
cars2

,car_model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2

In [13]:
df3=DataFrame(np.floor(np.random.rand(50).reshape(10,5)*100))
df3

      0     1     2     3     4
0  23.0  37.0  56.0  55.0  92.0
1   4.0  35.0  83.0  78.0  13.0
2  16.0  61.0  60.0  58.0  33.0
3  70.0  81.0  48.0  56.0  86.0
4  70.0  95.0  25.0  29.0  56.0
5  76.0  93.0  93.0  85.0  45.0
6   4.0  97.0  85.0  65.0  46.0
7  87.0  62.0  23.0  36.0  63.0
8  39.0  53.0  33.0  26.0  53.0
9  98.0  87.0  65.0  22.0  26.0

In [14]:
df3.columns=['Col1','Col2','Col3','Col4','Col5']
df3

   Col1  Col2  Col3  Col4  Col5
0  23.0  37.0  56.0  55.0  92.0
1   4.0  35.0  83.0  78.0  13.0
2  16.0  61.0  60.0  58.0  33.0
3  70.0  81.0  48.0  56.0  86.0
4  70.0  95.0  25.0  29.0  56.0
5  76.0  93.0  93.0  85.0  45.0
6   4.0  97.0  85.0  65.0  46.0
7  87.0  62.0  23.0  36.0  63.0
8  39.0  53.0  33.0  26.0  53.0
9  98.0  87.0  65.0  22.0  26.0

In [80]:
df3.columns

Index(['Col1', 'Col2', 'Col3', 'Col4', 'Col5'], dtype='object')

In [21]:
df3.loc[0:7,'Col1':'Col4']

   Col1  Col2  Col3  Col4
0  23.0  37.0  56.0  55.0
1   4.0  35.0  83.0  78.0
2  16.0  61.0  60.0  58.0
3  70.0  81.0  48.0  56.0
4  70.0  95.0  25.0  29.0
5  76.0  93.0  93.0  85.0
6   4.0  97.0  85.0  65.0
7  87.0  62.0  23.0  36.0

In [22]:
df3.iloc[0:7,0:2] # y index is exclusive, x is inclusive

   Col1  Col2
0  23.0  37.0
1   4.0  35.0
2  16.0  61.0
3  70.0  81.0
4  70.0  95.0
5  76.0  93.0
6   4.0  97.0

In [84]:
# Export to csv
df3.to_csv('NEW_DATA_FRAME.csv')

In [83]:
pwd

'C:\\Users\\DELL\\ipython notebook'

In [85]:
# Export to excel.
df3.to_excel('NEW_DATA_FRAME.xlsx')