# Understanding Nan - Not a Number

In [97]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [98]:
np.nan == True

False

In [99]:
np.nan ==0

False

In [100]:
np.nan==-1

False

In [101]:
np.nan==1

False

In [102]:
# Use whichever operator and get the output as True
np.nan != True

True

In [103]:
np.nan!=0

True

In [104]:
# Create a random DataFrame of 5 rows and 6 columns , check for any Nan values and see the output
df=DataFrame(np.floor(np.random.rand(30).reshape(5,6)*100))
df

      0     1     2     3     4     5
0  12.0  62.0  80.0  95.0   0.0  65.0
1  34.0  70.0  25.0   1.0   5.0  49.0
2  61.0  55.0  22.0  38.0   1.0   1.0
3  43.0  14.0  34.0  47.0   1.0  41.0
4  19.0  54.0  43.0   8.0  77.0  20.0

In [105]:
df==np.nan

       0      1      2      3      4      5
0  False  False  False  False  False  False
1  False  False  False  False  False  False
2  False  False  False  False  False  False
3  False  False  False  False  False  False
4  False  False  False  False  False  False

# Load the dataset

In [106]:
cars=pd.read_csv("mtcars.csv")
cars.head()

        car_model   mpg  cyl   disp   hp  ...   qsec  vs  am  gear  carb
0       Mazda RX4  21.0    6  160.0  110  ...  16.46   0   1     4     4
1   Mazda RX4 Wag  21.0    6  160.0  110  ...  17.02   0   1     4     4
2      Datsun 710  22.8    4  108.0   93  ...  18.61   1   1     4     1
3  Hornet 4 Drive  21.4    6  258.0  110  ...  19.44   1   0     3     1
4      Datsun 710  22.8    4  108.0   93  ...  18.61   1   1     4     1

[5 rows x 12 columns]

In [107]:
cars1=cars[(cars.mpg>30)]
cars1

         car_model   mpg  cyl  disp   hp  ...   qsec  vs  am  gear  carb
17        Fiat 128  32.4    4  78.7   66  ...  19.47   1   1     4     1
18     Honda Civic  30.4    4  75.7   52  ...  18.52   1   1     4     2
19  Toyota Corolla  33.9    4  71.1   65  ...  19.90   1   1     4     1
27    Lotus Europa  30.4    4  95.1  113  ...  16.90   1   1     5     2

[4 rows x 12 columns]

# Treating missing values in Python

In [108]:
cars.shape

(32, 12)

In [109]:
cars.isnull().sum()

car_model    0
mpg          0
cyl          0
disp         0
hp           0
drat         0
wt           0
qsec         0
vs           0
am           0
gear         0
carb         0
dtype: int64

In [110]:
cars.loc[5,'hp']=np.nan
cars.loc[3,'hp']=np.nan
cars.loc[6,'hp']=np.nan
cars.loc[5,'mpg']=np.nan
cars.loc[2,'mpg']=np.nan
cars.head(10)

        car_model   mpg  cyl   disp     hp  ...   qsec  vs  am  gear  carb
0       Mazda RX4  21.0    6  160.0  110.0  ...  16.46   0   1     4     4
1   Mazda RX4 Wag  21.0    6  160.0  110.0  ...  17.02   0   1     4     4
2      Datsun 710   NaN    4  108.0   93.0  ...  18.61   1   1     4     1
3  Hornet 4 Drive  21.4    6  258.0    NaN  ...  19.44   1   0     3     1
4      Datsun 710  22.8    4  108.0   93.0  ...  18.61   1   1     4     1
5         Valiant   NaN    6  225.0    NaN  ...  20.22   1   0     3     1
6      Duster 360  14.3    8  360.0    NaN  ...  15.84   0   0     3     4
7       Valiant 2  18.1    6  225.0  105.0  ...  20.22   1   0     3     1
8         Valiant  18.1    6  225.0  105.0  ...  20.22   1   0     3     1
9        Merc 280  19.2    6  167.6  123.0  ...  18.30   1   0     4     4

[10 rows x 12 columns]

In [111]:
cars.isnull().sum()

car_model    0
mpg          2
cyl          0
disp         0
hp           3
drat         0
wt           0
qsec         0
vs           0
am           0
gear         0
carb         0
dtype: int64

# Filling missing values with fillna()

In [112]:
cars.fillna(150)

              car_model    mpg  cyl   disp     hp  ...   qsec  vs  am  gear  carb
0             Mazda RX4   21.0    6  160.0  110.0  ...  16.46   0   1     4     4
1         Mazda RX4 Wag   21.0    6  160.0  110.0  ...  17.02   0   1     4     4
2            Datsun 710  150.0    4  108.0   93.0  ...  18.61   1   1     4     1
3        Hornet 4 Drive   21.4    6  258.0  150.0  ...  19.44   1   0     3     1
4            Datsun 710   22.8    4  108.0   93.0  ...  18.61   1   1     4     1
5               Valiant  150.0    6  225.0  150.0  ...  20.22   1   0     3     1
6            Duster 360   14.3    8  360.0  150.0  ...  15.84   0   0     3     4
7             Valiant 2   18.1    6  225.0  105.0  ...  20.22   1   0     3     1
8               Valiant   18.1    6  225.0  105.0  ...  20.22   1   0     3     1
9              Merc 280   19.2    6  167.6  123.0  ...  18.30   1   0     4     4
10            Merc 280C   17.8    6  167.6  123.0  ...  18.90   1   0     4     4
11           Merc 450SE   16.4    8  275.8  180.0  ...  17.40   0   0     3     3
12           Merc 450SL   17.3    8  275.8  180.0  ...  17.60   0   0     3     3
13          Merc 450SLC   15.2    8  275.8  180.0  ...  18.00   0   0     3     3
14   Cadillac Fleetwood   10.4    8  472.0  205.0  ...  17.98   0   0     3     4
15  Lincoln Continental   10.4    8  460.0  215.0  ...  17.82   0   0     3     4
16    Chrysler Imperial   14.7    8  440.0  230.0  ...  17.42   0   0     3     4
17             Fiat 128   32.4    4   78.7   66.0  ...  19.47   1   1     4     1
18          Honda Civic   30.4    4   75.7   52.0  ...  18.52   1   1     4     2
19       Toyota Corolla   33.9    4   71.1   65.0  ...  19.90   1   1     4     1
20        Toyota Corona   21.5    4  120.1   97.0  ...  20.01   1   0     3     1
21     Dodge Challenger   15.5    8  318.0  150.0  ...  16.87   0   0     3     2
22          AMC Javelin   15.2    8  304.0  150.0  ...  17.30   0   0     3     2
23           Camaro Z28   13.3    8  350.0  245.0  ...  15.41   0   0     3     4
24     Pontiac Firebird   19.2    8  400.0  175.0  ...  17.05   0   0     3     2
25            Fiat X1-9   27.3    4   79.0   66.0  ...  18.90   1   1     4     1
26        Porsche 914-2   26.0    4  120.3   91.0  ...  16.70   0   1     5     2
27         Lotus Europa   30.4    4   95.1  113.0  ...  16.90   1   1     5     2
28       Ford Pantera L   15.8    8  351.0  264.0  ...  14.50   0   1     5     4
29         Ferrari Dino   19.7    6  145.0  175.0  ...  15.50   0   1     5     6
30        Maserati Bora   15.0    8  301.0  335.0  ...  14.60   0   1     5     8
31           Volvo 142E   21.4    4  121.0  109.0  ...  18.60   1   1     4     2

[32 rows x 12 columns]

In [113]:
cars.head()

        car_model   mpg  cyl   disp     hp  ...   qsec  vs  am  gear  carb
0       Mazda RX4  21.0    6  160.0  110.0  ...  16.46   0   1     4     4
1   Mazda RX4 Wag  21.0    6  160.0  110.0  ...  17.02   0   1     4     4
2      Datsun 710   NaN    4  108.0   93.0  ...  18.61   1   1     4     1
3  Hornet 4 Drive  21.4    6  258.0    NaN  ...  19.44   1   0     3     1
4      Datsun 710  22.8    4  108.0   93.0  ...  18.61   1   1     4     1

[5 rows x 12 columns]

In [114]:
# Forward filling - Filling the value above the missing value
cars.fillna(method='ffill')

              car_model   mpg  cyl   disp     hp  ...   qsec  vs  am  gear  carb
0             Mazda RX4  21.0    6  160.0  110.0  ...  16.46   0   1     4     4
1         Mazda RX4 Wag  21.0    6  160.0  110.0  ...  17.02   0   1     4     4
2            Datsun 710  21.0    4  108.0   93.0  ...  18.61   1   1     4     1
3        Hornet 4 Drive  21.4    6  258.0   93.0  ...  19.44   1   0     3     1
4            Datsun 710  22.8    4  108.0   93.0  ...  18.61   1   1     4     1
5               Valiant  22.8    6  225.0   93.0  ...  20.22   1   0     3     1
6            Duster 360  14.3    8  360.0   93.0  ...  15.84   0   0     3     4
7             Valiant 2  18.1    6  225.0  105.0  ...  20.22   1   0     3     1
8               Valiant  18.1    6  225.0  105.0  ...  20.22   1   0     3     1
9              Merc 280  19.2    6  167.6  123.0  ...  18.30   1   0     4     4
10            Merc 280C  17.8    6  167.6  123.0  ...  18.90   1   0     4     4
11           Merc 450SE  16.4    8  275.8  180.0  ...  17.40   0   0     3     3
12           Merc 450SL  17.3    8  275.8  180.0  ...  17.60   0   0     3     3
13          Merc 450SLC  15.2    8  275.8  180.0  ...  18.00   0   0     3     3
14   Cadillac Fleetwood  10.4    8  472.0  205.0  ...  17.98   0   0     3     4
15  Lincoln Continental  10.4    8  460.0  215.0  ...  17.82   0   0     3     4
16    Chrysler Imperial  14.7    8  440.0  230.0  ...  17.42   0   0     3     4
17             Fiat 128  32.4    4   78.7   66.0  ...  19.47   1   1     4     1
18          Honda Civic  30.4    4   75.7   52.0  ...  18.52   1   1     4     2
19       Toyota Corolla  33.9    4   71.1   65.0  ...  19.90   1   1     4     1
20        Toyota Corona  21.5    4  120.1   97.0  ...  20.01   1   0     3     1
21     Dodge Challenger  15.5    8  318.0  150.0  ...  16.87   0   0     3     2
22          AMC Javelin  15.2    8  304.0  150.0  ...  17.30   0   0     3     2
23           Camaro Z28  13.3    8  350.0  245.0  ...  15.41   0   0     3     4
24     Pontiac Firebird  19.2    8  400.0  175.0  ...  17.05   0   0     3     2
25            Fiat X1-9  27.3    4   79.0   66.0  ...  18.90   1   1     4     1
26        Porsche 914-2  26.0    4  120.3   91.0  ...  16.70   0   1     5     2
27         Lotus Europa  30.4    4   95.1  113.0  ...  16.90   1   1     5     2
28       Ford Pantera L  15.8    8  351.0  264.0  ...  14.50   0   1     5     4
29         Ferrari Dino  19.7    6  145.0  175.0  ...  15.50   0   1     5     6
30        Maserati Bora  15.0    8  301.0  335.0  ...  14.60   0   1     5     8
31           Volvo 142E  21.4    4  121.0  109.0  ...  18.60   1   1     4     2

[32 rows x 12 columns]

In [115]:
# Backward filling - Filling the value below missing value
cars.fillna(method='bfill')

              car_model   mpg  cyl   disp     hp  ...   qsec  vs  am  gear  carb
0             Mazda RX4  21.0    6  160.0  110.0  ...  16.46   0   1     4     4
1         Mazda RX4 Wag  21.0    6  160.0  110.0  ...  17.02   0   1     4     4
2            Datsun 710  21.4    4  108.0   93.0  ...  18.61   1   1     4     1
3        Hornet 4 Drive  21.4    6  258.0   93.0  ...  19.44   1   0     3     1
4            Datsun 710  22.8    4  108.0   93.0  ...  18.61   1   1     4     1
5               Valiant  14.3    6  225.0  105.0  ...  20.22   1   0     3     1
6            Duster 360  14.3    8  360.0  105.0  ...  15.84   0   0     3     4
7             Valiant 2  18.1    6  225.0  105.0  ...  20.22   1   0     3     1
8               Valiant  18.1    6  225.0  105.0  ...  20.22   1   0     3     1
9              Merc 280  19.2    6  167.6  123.0  ...  18.30   1   0     4     4
10            Merc 280C  17.8    6  167.6  123.0  ...  18.90   1   0     4     4
11           Merc 450SE  16.4    8  275.8  180.0  ...  17.40   0   0     3     3
12           Merc 450SL  17.3    8  275.8  180.0  ...  17.60   0   0     3     3
13          Merc 450SLC  15.2    8  275.8  180.0  ...  18.00   0   0     3     3
14   Cadillac Fleetwood  10.4    8  472.0  205.0  ...  17.98   0   0     3     4
15  Lincoln Continental  10.4    8  460.0  215.0  ...  17.82   0   0     3     4
16    Chrysler Imperial  14.7    8  440.0  230.0  ...  17.42   0   0     3     4
17             Fiat 128  32.4    4   78.7   66.0  ...  19.47   1   1     4     1
18          Honda Civic  30.4    4   75.7   52.0  ...  18.52   1   1     4     2
19       Toyota Corolla  33.9    4   71.1   65.0  ...  19.90   1   1     4     1
20        Toyota Corona  21.5    4  120.1   97.0  ...  20.01   1   0     3     1
21     Dodge Challenger  15.5    8  318.0  150.0  ...  16.87   0   0     3     2
22          AMC Javelin  15.2    8  304.0  150.0  ...  17.30   0   0     3     2
23           Camaro Z28  13.3    8  350.0  245.0  ...  15.41   0   0     3     4
24     Pontiac Firebird  19.2    8  400.0  175.0  ...  17.05   0   0     3     2
25            Fiat X1-9  27.3    4   79.0   66.0  ...  18.90   1   1     4     1
26        Porsche 914-2  26.0    4  120.3   91.0  ...  16.70   0   1     5     2
27         Lotus Europa  30.4    4   95.1  113.0  ...  16.90   1   1     5     2
28       Ford Pantera L  15.8    8  351.0  264.0  ...  14.50   0   1     5     4
29         Ferrari Dino  19.7    6  145.0  175.0  ...  15.50   0   1     5     6
30        Maserati Bora  15.0    8  301.0  335.0  ...  14.60   0   1     5     8
31           Volvo 142E  21.4    4  121.0  109.0  ...  18.60   1   1     4     2

[32 rows x 12 columns]

In [116]:
# Treating the missing value with mean
cars.fillna(cars.mean()) # normally leads better results

              car_model        mpg  cyl   disp  ...  vs  am  gear  carb
0             Mazda RX4  21.000000    6  160.0  ...   0   1     4     4
1         Mazda RX4 Wag  21.000000    6  160.0  ...   0   1     4     4
2            Datsun 710  19.836667    4  108.0  ...   1   1     4     1
3        Hornet 4 Drive  21.400000    6  258.0  ...   1   0     3     1
4            Datsun 710  22.800000    4  108.0  ...   1   1     4     1
5               Valiant  19.836667    6  225.0  ...   1   0     3     1
6            Duster 360  14.300000    8  360.0  ...   0   0     3     4
7             Valiant 2  18.100000    6  225.0  ...   1   0     3     1
8               Valiant  18.100000    6  225.0  ...   1   0     3     1
9              Merc 280  19.200000    6  167.6  ...   1   0     4     4
10            Merc 280C  17.800000    6  167.6  ...   1   0     4     4
11           Merc 450SE  16.400000    8  275.8  ...   0   0     3     3
12           Merc 450SL  17.300000    8  275.8  ...   0   0     3     3
13          Merc 450SLC  15.200000    8  275.8  ...   0   0     3     3
14   Cadillac Fleetwood  10.400000    8  472.0  ...   0   0     3     4
15  Lincoln Continental  10.400000    8  460.0  ...   0   0     3     4
16    Chrysler Imperial  14.700000    8  440.0  ...   0   0     3     4
17             Fiat 128  32.400000    4   78.7  ...   1   1     4     1
18          Honda Civic  30.400000    4   75.7  ...   1   1     4     2
19       Toyota Corolla  33.900000    4   71.1  ...   1   1     4     1
20        Toyota Corona  21.500000    4  120.1  ...   1   0     3     1
21     Dodge Challenger  15.500000    8  318.0  ...   0   0     3     2
22          AMC Javelin  15.200000    8  304.0  ...   0   0     3     2
23           Camaro Z28  13.300000    8  350.0  ...   0   0     3     4
24     Pontiac Firebird  19.200000    8  400.0  ...   0   0     3     2
25            Fiat X1-9  27.300000    4   79.0  ...   1   1     4     1
26        Porsche 914-2  26.000000    4  120.3  ...   0   1     5     2
27         Lotus Europa  30.400000    4   95.1  ...   1   1     5     2
28       Ford Pantera L  15.800000    8  351.0  ...   0   1     5     4
29         Ferrari Dino  19.700000    6  145.0  ...   0   1     5     6
30        Maserati Bora  15.000000    8  301.0  ...   0   1     5     8
31           Volvo 142E  21.400000    4  121.0  ...   1   1     4     2

[32 rows x 12 columns]

# Removing the row with missing values

In [117]:
cars.dropna()

              car_model   mpg  cyl   disp     hp  ...   qsec  vs  am  gear  carb
0             Mazda RX4  21.0    6  160.0  110.0  ...  16.46   0   1     4     4
1         Mazda RX4 Wag  21.0    6  160.0  110.0  ...  17.02   0   1     4     4
4            Datsun 710  22.8    4  108.0   93.0  ...  18.61   1   1     4     1
7             Valiant 2  18.1    6  225.0  105.0  ...  20.22   1   0     3     1
8               Valiant  18.1    6  225.0  105.0  ...  20.22   1   0     3     1
9              Merc 280  19.2    6  167.6  123.0  ...  18.30   1   0     4     4
10            Merc 280C  17.8    6  167.6  123.0  ...  18.90   1   0     4     4
11           Merc 450SE  16.4    8  275.8  180.0  ...  17.40   0   0     3     3
12           Merc 450SL  17.3    8  275.8  180.0  ...  17.60   0   0     3     3
13          Merc 450SLC  15.2    8  275.8  180.0  ...  18.00   0   0     3     3
14   Cadillac Fleetwood  10.4    8  472.0  205.0  ...  17.98   0   0     3     4
15  Lincoln Continental  10.4    8  460.0  215.0  ...  17.82   0   0     3     4
16    Chrysler Imperial  14.7    8  440.0  230.0  ...  17.42   0   0     3     4
17             Fiat 128  32.4    4   78.7   66.0  ...  19.47   1   1     4     1
18          Honda Civic  30.4    4   75.7   52.0  ...  18.52   1   1     4     2
19       Toyota Corolla  33.9    4   71.1   65.0  ...  19.90   1   1     4     1
20        Toyota Corona  21.5    4  120.1   97.0  ...  20.01   1   0     3     1
21     Dodge Challenger  15.5    8  318.0  150.0  ...  16.87   0   0     3     2
22          AMC Javelin  15.2    8  304.0  150.0  ...  17.30   0   0     3     2
23           Camaro Z28  13.3    8  350.0  245.0  ...  15.41   0   0     3     4
24     Pontiac Firebird  19.2    8  400.0  175.0  ...  17.05   0   0     3     2
25            Fiat X1-9  27.3    4   79.0   66.0  ...  18.90   1   1     4     1
26        Porsche 914-2  26.0    4  120.3   91.0  ...  16.70   0   1     5     2
27         Lotus Europa  30.4    4   95.1  113.0  ...  16.90   1   1     5     2
28       Ford Pantera L  15.8    8  351.0  264.0  ...  14.50   0   1     5     4
29         Ferrari Dino  19.7    6  145.0  175.0  ...  15.50   0   1     5     6
30        Maserati Bora  15.0    8  301.0  335.0  ...  14.60   0   1     5     8
31           Volvo 142E  21.4    4  121.0  109.0  ...  18.60   1   1     4     2

[28 rows x 12 columns]

In [118]:
cars.head()

        car_model   mpg  cyl   disp     hp  ...   qsec  vs  am  gear  carb
0       Mazda RX4  21.0    6  160.0  110.0  ...  16.46   0   1     4     4
1   Mazda RX4 Wag  21.0    6  160.0  110.0  ...  17.02   0   1     4     4
2      Datsun 710   NaN    4  108.0   93.0  ...  18.61   1   1     4     1
3  Hornet 4 Drive  21.4    6  258.0    NaN  ...  19.44   1   0     3     1
4      Datsun 710  22.8    4  108.0   93.0  ...  18.61   1   1     4     1

[5 rows x 12 columns]

In [119]:
cars.dropna(inplace=True) # Drops the misssing values

In [120]:
cars.head(10)

        car_model   mpg  cyl   disp     hp  ...   qsec  vs  am  gear  carb
0       Mazda RX4  21.0    6  160.0  110.0  ...  16.46   0   1     4     4
1   Mazda RX4 Wag  21.0    6  160.0  110.0  ...  17.02   0   1     4     4
4      Datsun 710  22.8    4  108.0   93.0  ...  18.61   1   1     4     1
7       Valiant 2  18.1    6  225.0  105.0  ...  20.22   1   0     3     1
8         Valiant  18.1    6  225.0  105.0  ...  20.22   1   0     3     1
9        Merc 280  19.2    6  167.6  123.0  ...  18.30   1   0     4     4
10      Merc 280C  17.8    6  167.6  123.0  ...  18.90   1   0     4     4
11     Merc 450SE  16.4    8  275.8  180.0  ...  17.40   0   0     3     3
12     Merc 450SL  17.3    8  275.8  180.0  ...  17.60   0   0     3     3
13    Merc 450SLC  15.2    8  275.8  180.0  ...  18.00   0   0     3     3

[10 rows x 12 columns]

In [121]:
cars.isnull().sum()

car_model    0
mpg          0
cyl          0
disp         0
hp           0
drat         0
wt           0
qsec         0
vs           0
am           0
gear         0
carb         0
dtype: int64

In [122]:
cars.dropna(how='all') # only drops rows when all columns of that row is empty

              car_model   mpg  cyl   disp     hp  ...   qsec  vs  am  gear  carb
0             Mazda RX4  21.0    6  160.0  110.0  ...  16.46   0   1     4     4
1         Mazda RX4 Wag  21.0    6  160.0  110.0  ...  17.02   0   1     4     4
4            Datsun 710  22.8    4  108.0   93.0  ...  18.61   1   1     4     1
7             Valiant 2  18.1    6  225.0  105.0  ...  20.22   1   0     3     1
8               Valiant  18.1    6  225.0  105.0  ...  20.22   1   0     3     1
9              Merc 280  19.2    6  167.6  123.0  ...  18.30   1   0     4     4
10            Merc 280C  17.8    6  167.6  123.0  ...  18.90   1   0     4     4
11           Merc 450SE  16.4    8  275.8  180.0  ...  17.40   0   0     3     3
12           Merc 450SL  17.3    8  275.8  180.0  ...  17.60   0   0     3     3
13          Merc 450SLC  15.2    8  275.8  180.0  ...  18.00   0   0     3     3
14   Cadillac Fleetwood  10.4    8  472.0  205.0  ...  17.98   0   0     3     4
15  Lincoln Continental  10.4    8  460.0  215.0  ...  17.82   0   0     3     4
16    Chrysler Imperial  14.7    8  440.0  230.0  ...  17.42   0   0     3     4
17             Fiat 128  32.4    4   78.7   66.0  ...  19.47   1   1     4     1
18          Honda Civic  30.4    4   75.7   52.0  ...  18.52   1   1     4     2
19       Toyota Corolla  33.9    4   71.1   65.0  ...  19.90   1   1     4     1
20        Toyota Corona  21.5    4  120.1   97.0  ...  20.01   1   0     3     1
21     Dodge Challenger  15.5    8  318.0  150.0  ...  16.87   0   0     3     2
22          AMC Javelin  15.2    8  304.0  150.0  ...  17.30   0   0     3     2
23           Camaro Z28  13.3    8  350.0  245.0  ...  15.41   0   0     3     4
24     Pontiac Firebird  19.2    8  400.0  175.0  ...  17.05   0   0     3     2
25            Fiat X1-9  27.3    4   79.0   66.0  ...  18.90   1   1     4     1
26        Porsche 914-2  26.0    4  120.3   91.0  ...  16.70   0   1     5     2
27         Lotus Europa  30.4    4   95.1  113.0  ...  16.90   1   1     5     2
28       Ford Pantera L  15.8    8  351.0  264.0  ...  14.50   0   1     5     4
29         Ferrari Dino  19.7    6  145.0  175.0  ...  15.50   0   1     5     6
30        Maserati Bora  15.0    8  301.0  335.0  ...  14.60   0   1     5     8
31           Volvo 142E  21.4    4  121.0  109.0  ...  18.60   1   1     4     2

[28 rows x 12 columns]

# Removing duplicates

In [123]:
# Creating a DataFrame using Dictionary
data=DataFrame({'col 1':[1,2,2,3,3,3,4,4],
                    'col 2':['a','b','b','c','c','c','d','c'],
                    'col 3':['A','B','B','C','C','C','D','D']})
data

   col 1 col 2 col 3
0      1     a     A
1      2     b     B
2      2     b     B
3      3     c     C
4      3     c     C
5      3     c     C
6      4     d     D
7      4     c     D

In [124]:
data.duplicated()

0    False
1    False
2     True
3    False
4     True
5     True
6    False
7    False
dtype: bool

In [125]:
data.drop_duplicates() # drop rows with the same values in all the columns

   col 1 col 2 col 3
0      1     a     A
1      2     b     B
3      3     c     C
6      4     d     D
7      4     c     D

In [126]:
data.drop_duplicates('col 3')

   col 1 col 2 col 3
0      1     a     A
1      2     b     B
3      3     c     C
6      4     d     D

In [127]:
data.transpose()

       0  1  2  3  4  5  6  7
col 1  1  2  2  3  3  3  4  4
col 2  a  b  b  c  c  c  d  c
col 3  A  B  B  C  C  C  D  D

# Sorting the Data in DataFrame

In [128]:
cars.sort_values('hp',ascending=False)

              car_model   mpg  cyl   disp     hp  ...   qsec  vs  am  gear  carb
30        Maserati Bora  15.0    8  301.0  335.0  ...  14.60   0   1     5     8
28       Ford Pantera L  15.8    8  351.0  264.0  ...  14.50   0   1     5     4
23           Camaro Z28  13.3    8  350.0  245.0  ...  15.41   0   0     3     4
16    Chrysler Imperial  14.7    8  440.0  230.0  ...  17.42   0   0     3     4
15  Lincoln Continental  10.4    8  460.0  215.0  ...  17.82   0   0     3     4
14   Cadillac Fleetwood  10.4    8  472.0  205.0  ...  17.98   0   0     3     4
13          Merc 450SLC  15.2    8  275.8  180.0  ...  18.00   0   0     3     3
11           Merc 450SE  16.4    8  275.8  180.0  ...  17.40   0   0     3     3
12           Merc 450SL  17.3    8  275.8  180.0  ...  17.60   0   0     3     3
29         Ferrari Dino  19.7    6  145.0  175.0  ...  15.50   0   1     5     6
24     Pontiac Firebird  19.2    8  400.0  175.0  ...  17.05   0   0     3     2
21     Dodge Challenger  15.5    8  318.0  150.0  ...  16.87   0   0     3     2
22          AMC Javelin  15.2    8  304.0  150.0  ...  17.30   0   0     3     2
10            Merc 280C  17.8    6  167.6  123.0  ...  18.90   1   0     4     4
9              Merc 280  19.2    6  167.6  123.0  ...  18.30   1   0     4     4
27         Lotus Europa  30.4    4   95.1  113.0  ...  16.90   1   1     5     2
1         Mazda RX4 Wag  21.0    6  160.0  110.0  ...  17.02   0   1     4     4
0             Mazda RX4  21.0    6  160.0  110.0  ...  16.46   0   1     4     4
31           Volvo 142E  21.4    4  121.0  109.0  ...  18.60   1   1     4     2
8               Valiant  18.1    6  225.0  105.0  ...  20.22   1   0     3     1
7             Valiant 2  18.1    6  225.0  105.0  ...  20.22   1   0     3     1
20        Toyota Corona  21.5    4  120.1   97.0  ...  20.01   1   0     3     1
4            Datsun 710  22.8    4  108.0   93.0  ...  18.61   1   1     4     1
26        Porsche 914-2  26.0    4  120.3   91.0  ...  16.70   0   1     5     2
25            Fiat X1-9  27.3    4   79.0   66.0  ...  18.90   1   1     4     1
17             Fiat 128  32.4    4   78.7   66.0  ...  19.47   1   1     4     1
19       Toyota Corolla  33.9    4   71.1   65.0  ...  19.90   1   1     4     1
18          Honda Civic  30.4    4   75.7   52.0  ...  18.52   1   1     4     2

[28 rows x 12 columns]

In [129]:
cars.sort_values('mpg',ascending=True).head(3)

              car_model   mpg  cyl   disp     hp  ...   qsec  vs  am  gear  carb
15  Lincoln Continental  10.4    8  460.0  215.0  ...  17.82   0   0     3     4
14   Cadillac Fleetwood  10.4    8  472.0  205.0  ...  17.98   0   0     3     4
23           Camaro Z28  13.3    8  350.0  245.0  ...  15.41   0   0     3     4

[3 rows x 12 columns]

# Transforming Data and Feature Creation

In [130]:
cars.shape

(28, 12)

In [131]:
# Adding new records or row
new_data=DataFrame(['Tata Nano',40,2,120,60,2.5,1.1,10,0,0,4,2])
new_data=new_data.transpose()
new_data

           0   1  2    3   4    5    6   7  8  9 10 11
0  Tata Nano  40  2  120  60  2.5  1.1  10  0  0  4  2

In [132]:
cars.columns

Index(['car_model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [133]:
new_data.columns=['car_model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb']

In [134]:
new_data

   car_model mpg cyl disp  hp drat   wt qsec vs am gear carb
0  Tata Nano  40   2  120  60  2.5  1.1   10  0  0    4    2

In [135]:
cars_updated=pd.concat([cars,new_data],ignore_index=True)
cars_updated

              car_model   mpg cyl   disp   hp  ...   qsec vs am gear carb
0             Mazda RX4    21   6    160  110  ...  16.46  0  1    4    4
1         Mazda RX4 Wag    21   6    160  110  ...  17.02  0  1    4    4
2            Datsun 710  22.8   4    108   93  ...  18.61  1  1    4    1
3             Valiant 2  18.1   6    225  105  ...  20.22  1  0    3    1
4               Valiant  18.1   6    225  105  ...  20.22  1  0    3    1
5              Merc 280  19.2   6  167.6  123  ...   18.3  1  0    4    4
6             Merc 280C  17.8   6  167.6  123  ...   18.9  1  0    4    4
7            Merc 450SE  16.4   8  275.8  180  ...   17.4  0  0    3    3
8            Merc 450SL  17.3   8  275.8  180  ...   17.6  0  0    3    3
9           Merc 450SLC  15.2   8  275.8  180  ...     18  0  0    3    3
10   Cadillac Fleetwood  10.4   8    472  205  ...  17.98  0  0    3    4
11  Lincoln Continental  10.4   8    460  215  ...  17.82  0  0    3    4
12    Chrysler Imperial  14.7   8    440  230  ...  17.42  0  0    3    4
13             Fiat 128  32.4   4   78.7   66  ...  19.47  1  1    4    1
14          Honda Civic  30.4   4   75.7   52  ...  18.52  1  1    4    2
15       Toyota Corolla  33.9   4   71.1   65  ...   19.9  1  1    4    1
16        Toyota Corona  21.5   4  120.1   97  ...  20.01  1  0    3    1
17     Dodge Challenger  15.5   8    318  150  ...  16.87  0  0    3    2
18          AMC Javelin  15.2   8    304  150  ...   17.3  0  0    3    2
19           Camaro Z28  13.3   8    350  245  ...  15.41  0  0    3    4
20     Pontiac Firebird  19.2   8    400  175  ...  17.05  0  0    3    2
21            Fiat X1-9  27.3   4     79   66  ...   18.9  1  1    4    1
22        Porsche 914-2    26   4  120.3   91  ...   16.7  0  1    5    2
23         Lotus Europa  30.4   4   95.1  113  ...   16.9  1  1    5    2
24       Ford Pantera L  15.8   8    351  264  ...   14.5  0  1    5    4
25         Ferrari Dino  19.7   6    145  175  ...   15.5  0  1    5    6
26        Maserati Bora    15   8    301  335  ...   14.6  0  1    5    8
27           Volvo 142E  21.4   4    121  109  ...   18.6  1  1    4    2
28            Tata Nano    40   2    120   60  ...     10  0  0    4    2

[29 rows x 12 columns]

In [136]:
cars_updated.tail(2)

     car_model   mpg cyl disp   hp  drat    wt  qsec vs am gear carb
27  Volvo 142E  21.4   4  121  109  4.11  2.78  18.6  1  1    4    2
28   Tata Nano    40   2  120   60   2.5   1.1    10  0  0    4    2

# Feature Creation

In [137]:
# Create new columns : Bangalore, 0,1; with cars >20 mpg as 1 and <=20 as 0

In [138]:
cars_updated.columns

Index(['car_model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [139]:
cars_updated.loc[cars_updated.mpg>20 ,'Bangalore'] =1
cars_updated.loc[cars_updated.mpg<=20, 'Bangalore']=0

In [140]:
cars_updated

              car_model   mpg cyl   disp   hp  ... vs am gear carb Bangalore
0             Mazda RX4    21   6    160  110  ...  0  1    4    4       1.0
1         Mazda RX4 Wag    21   6    160  110  ...  0  1    4    4       1.0
2            Datsun 710  22.8   4    108   93  ...  1  1    4    1       1.0
3             Valiant 2  18.1   6    225  105  ...  1  0    3    1       0.0
4               Valiant  18.1   6    225  105  ...  1  0    3    1       0.0
5              Merc 280  19.2   6  167.6  123  ...  1  0    4    4       0.0
6             Merc 280C  17.8   6  167.6  123  ...  1  0    4    4       0.0
7            Merc 450SE  16.4   8  275.8  180  ...  0  0    3    3       0.0
8            Merc 450SL  17.3   8  275.8  180  ...  0  0    3    3       0.0
9           Merc 450SLC  15.2   8  275.8  180  ...  0  0    3    3       0.0
10   Cadillac Fleetwood  10.4   8    472  205  ...  0  0    3    4       0.0
11  Lincoln Continental  10.4   8    460  215  ...  0  0    3    4       0.0
12    Chrysler Imperial  14.7   8    440  230  ...  0  0    3    4       0.0
13             Fiat 128  32.4   4   78.7   66  ...  1  1    4    1       1.0
14          Honda Civic  30.4   4   75.7   52  ...  1  1    4    2       1.0
15       Toyota Corolla  33.9   4   71.1   65  ...  1  1    4    1       1.0
16        Toyota Corona  21.5   4  120.1   97  ...  1  0    3    1       1.0
17     Dodge Challenger  15.5   8    318  150  ...  0  0    3    2       0.0
18          AMC Javelin  15.2   8    304  150  ...  0  0    3    2       0.0
19           Camaro Z28  13.3   8    350  245  ...  0  0    3    4       0.0
20     Pontiac Firebird  19.2   8    400  175  ...  0  0    3    2       0.0
21            Fiat X1-9  27.3   4     79   66  ...  1  1    4    1       1.0
22        Porsche 914-2    26   4  120.3   91  ...  0  1    5    2       1.0
23         Lotus Europa  30.4   4   95.1  113  ...  1  1    5    2       1.0
24       Ford Pantera L  15.8   8    351  264  ...  0  1    5    4       0.0
25         Ferrari Dino  19.7   6    145  175  ...  0  1    5    6       0.0
26        Maserati Bora    15   8    301  335  ...  0  1    5    8       0.0
27           Volvo 142E  21.4   4    121  109  ...  1  1    4    2       1.0
28            Tata Nano    40   2    120   60  ...  0  0    4    2       1.0

[29 rows x 13 columns]

In [145]:
# Create a new feature , light cars with wt >3 as 0 and <=3 as 1
cars.loc[cars.wt>3 ,'light cars'] =0
cars.loc[cars.wt<=3, 'light cars']=1

In [146]:
cars

              car_model   mpg  cyl   disp  ...  am  gear  carb  light cars
0             Mazda RX4  21.0    6  160.0  ...   1     4     4         1.0
1         Mazda RX4 Wag  21.0    6  160.0  ...   1     4     4         1.0
4            Datsun 710  22.8    4  108.0  ...   1     4     1         1.0
7             Valiant 2  18.1    6  225.0  ...   0     3     1         0.0
8               Valiant  18.1    6  225.0  ...   0     3     1         0.0
9              Merc 280  19.2    6  167.6  ...   0     4     4         0.0
10            Merc 280C  17.8    6  167.6  ...   0     4     4         0.0
11           Merc 450SE  16.4    8  275.8  ...   0     3     3         0.0
12           Merc 450SL  17.3    8  275.8  ...   0     3     3         0.0
13          Merc 450SLC  15.2    8  275.8  ...   0     3     3         0.0
14   Cadillac Fleetwood  10.4    8  472.0  ...   0     3     4         0.0
15  Lincoln Continental  10.4    8  460.0  ...   0     3     4         0.0
16    Chrysler Imperial  14.7    8  440.0  ...   0     3     4         0.0
17             Fiat 128  32.4    4   78.7  ...   1     4     1         1.0
18          Honda Civic  30.4    4   75.7  ...   1     4     2         1.0
19       Toyota Corolla  33.9    4   71.1  ...   1     4     1         1.0
20        Toyota Corona  21.5    4  120.1  ...   0     3     1         1.0
21     Dodge Challenger  15.5    8  318.0  ...   0     3     2         0.0
22          AMC Javelin  15.2    8  304.0  ...   0     3     2         0.0
23           Camaro Z28  13.3    8  350.0  ...   0     3     4         0.0
24     Pontiac Firebird  19.2    8  400.0  ...   0     3     2         0.0
25            Fiat X1-9  27.3    4   79.0  ...   1     4     1         1.0
26        Porsche 914-2  26.0    4  120.3  ...   1     5     2         1.0
27         Lotus Europa  30.4    4   95.1  ...   1     5     2         1.0
28       Ford Pantera L  15.8    8  351.0  ...   1     5     4         0.0
29         Ferrari Dino  19.7    6  145.0  ...   1     5     6         1.0
30        Maserati Bora  15.0    8  301.0  ...   1     5     8         0.0
31           Volvo 142E  21.4    4  121.0  ...   1     4     2         1.0

[28 rows x 13 columns]

In [143]:
cars_updated.drop('mpg',axis=1)

              car_model cyl   disp   hp  drat  ... vs am gear carb Bangalore
0             Mazda RX4   6    160  110   3.9  ...  0  1    4    4       1.0
1         Mazda RX4 Wag   6    160  110   3.9  ...  0  1    4    4       1.0
2            Datsun 710   4    108   93  3.85  ...  1  1    4    1       1.0
3             Valiant 2   6    225  105  2.76  ...  1  0    3    1       0.0
4               Valiant   6    225  105  2.76  ...  1  0    3    1       0.0
5              Merc 280   6  167.6  123  3.92  ...  1  0    4    4       0.0
6             Merc 280C   6  167.6  123  3.92  ...  1  0    4    4       0.0
7            Merc 450SE   8  275.8  180  3.07  ...  0  0    3    3       0.0
8            Merc 450SL   8  275.8  180  3.07  ...  0  0    3    3       0.0
9           Merc 450SLC   8  275.8  180  3.07  ...  0  0    3    3       0.0
10   Cadillac Fleetwood   8    472  205  2.93  ...  0  0    3    4       0.0
11  Lincoln Continental   8    460  215     3  ...  0  0    3    4       0.0
12    Chrysler Imperial   8    440  230  3.23  ...  0  0    3    4       0.0
13             Fiat 128   4   78.7   66  4.08  ...  1  1    4    1       1.0
14          Honda Civic   4   75.7   52  4.93  ...  1  1    4    2       1.0
15       Toyota Corolla   4   71.1   65  4.22  ...  1  1    4    1       1.0
16        Toyota Corona   4  120.1   97   3.7  ...  1  0    3    1       1.0
17     Dodge Challenger   8    318  150  2.76  ...  0  0    3    2       0.0
18          AMC Javelin   8    304  150  3.15  ...  0  0    3    2       0.0
19           Camaro Z28   8    350  245  3.73  ...  0  0    3    4       0.0
20     Pontiac Firebird   8    400  175  3.08  ...  0  0    3    2       0.0
21            Fiat X1-9   4     79   66  4.08  ...  1  1    4    1       1.0
22        Porsche 914-2   4  120.3   91  4.43  ...  0  1    5    2       1.0
23         Lotus Europa   4   95.1  113  3.77  ...  1  1    5    2       1.0
24       Ford Pantera L   8    351  264  4.22  ...  0  1    5    4       0.0
25         Ferrari Dino   6    145  175  3.62  ...  0  1    5    6       0.0
26        Maserati Bora   8    301  335  3.54  ...  0  1    5    8       0.0
27           Volvo 142E   4    121  109  4.11  ...  1  1    4    2       1.0
28            Tata Nano   2    120   60   2.5  ...  0  0    4    2       1.0

[29 rows x 12 columns]

In [144]:
cars_updated.drop('Bangalore',axis=1)

              car_model   mpg cyl   disp   hp  ...   qsec vs am gear carb
0             Mazda RX4    21   6    160  110  ...  16.46  0  1    4    4
1         Mazda RX4 Wag    21   6    160  110  ...  17.02  0  1    4    4
2            Datsun 710  22.8   4    108   93  ...  18.61  1  1    4    1
3             Valiant 2  18.1   6    225  105  ...  20.22  1  0    3    1
4               Valiant  18.1   6    225  105  ...  20.22  1  0    3    1
5              Merc 280  19.2   6  167.6  123  ...   18.3  1  0    4    4
6             Merc 280C  17.8   6  167.6  123  ...   18.9  1  0    4    4
7            Merc 450SE  16.4   8  275.8  180  ...   17.4  0  0    3    3
8            Merc 450SL  17.3   8  275.8  180  ...   17.6  0  0    3    3
9           Merc 450SLC  15.2   8  275.8  180  ...     18  0  0    3    3
10   Cadillac Fleetwood  10.4   8    472  205  ...  17.98  0  0    3    4
11  Lincoln Continental  10.4   8    460  215  ...  17.82  0  0    3    4
12    Chrysler Imperial  14.7   8    440  230  ...  17.42  0  0    3    4
13             Fiat 128  32.4   4   78.7   66  ...  19.47  1  1    4    1
14          Honda Civic  30.4   4   75.7   52  ...  18.52  1  1    4    2
15       Toyota Corolla  33.9   4   71.1   65  ...   19.9  1  1    4    1
16        Toyota Corona  21.5   4  120.1   97  ...  20.01  1  0    3    1
17     Dodge Challenger  15.5   8    318  150  ...  16.87  0  0    3    2
18          AMC Javelin  15.2   8    304  150  ...   17.3  0  0    3    2
19           Camaro Z28  13.3   8    350  245  ...  15.41  0  0    3    4
20     Pontiac Firebird  19.2   8    400  175  ...  17.05  0  0    3    2
21            Fiat X1-9  27.3   4     79   66  ...   18.9  1  1    4    1
22        Porsche 914-2    26   4  120.3   91  ...   16.7  0  1    5    2
23         Lotus Europa  30.4   4   95.1  113  ...   16.9  1  1    5    2
24       Ford Pantera L  15.8   8    351  264  ...   14.5  0  1    5    4
25         Ferrari Dino  19.7   6    145  175  ...   15.5  0  1    5    6
26        Maserati Bora    15   8    301  335  ...   14.6  0  1    5    8
27           Volvo 142E  21.4   4    121  109  ...   18.6  1  1    4    2
28            Tata Nano    40   2    120   60  ...     10  0  0    4    2

[29 rows x 12 columns]

In [152]:
cars.loc[cars.mpg>20 ,'Bangalore'] =1
cars.loc[cars.mpg<=20, 'Bangalore']=0

In [153]:
cars

              car_model   mpg  cyl   disp  ...  gear  carb  light cars  Bangalore
0             Mazda RX4  21.0    6  160.0  ...     4     4         1.0        1.0
1         Mazda RX4 Wag  21.0    6  160.0  ...     4     4         1.0        1.0
4            Datsun 710  22.8    4  108.0  ...     4     1         1.0        1.0
7             Valiant 2  18.1    6  225.0  ...     3     1         0.0        0.0
8               Valiant  18.1    6  225.0  ...     3     1         0.0        0.0
9              Merc 280  19.2    6  167.6  ...     4     4         0.0        0.0
10            Merc 280C  17.8    6  167.6  ...     4     4         0.0        0.0
11           Merc 450SE  16.4    8  275.8  ...     3     3         0.0        0.0
12           Merc 450SL  17.3    8  275.8  ...     3     3         0.0        0.0
13          Merc 450SLC  15.2    8  275.8  ...     3     3         0.0        0.0
14   Cadillac Fleetwood  10.4    8  472.0  ...     3     4         0.0        0.0
15  Lincoln Continental  10.4    8  460.0  ...     3     4         0.0        0.0
16    Chrysler Imperial  14.7    8  440.0  ...     3     4         0.0        0.0
17             Fiat 128  32.4    4   78.7  ...     4     1         1.0        1.0
18          Honda Civic  30.4    4   75.7  ...     4     2         1.0        1.0
19       Toyota Corolla  33.9    4   71.1  ...     4     1         1.0        1.0
20        Toyota Corona  21.5    4  120.1  ...     3     1         1.0        1.0
21     Dodge Challenger  15.5    8  318.0  ...     3     2         0.0        0.0
22          AMC Javelin  15.2    8  304.0  ...     3     2         0.0        0.0
23           Camaro Z28  13.3    8  350.0  ...     3     4         0.0        0.0
24     Pontiac Firebird  19.2    8  400.0  ...     3     2         0.0        0.0
25            Fiat X1-9  27.3    4   79.0  ...     4     1         1.0        1.0
26        Porsche 914-2  26.0    4  120.3  ...     5     2         1.0        1.0
27         Lotus Europa  30.4    4   95.1  ...     5     2         1.0        1.0
28       Ford Pantera L  15.8    8  351.0  ...     5     4         0.0        0.0
29         Ferrari Dino  19.7    6  145.0  ...     5     6         1.0        0.0
30        Maserati Bora  15.0    8  301.0  ...     5     8         0.0        0.0
31           Volvo 142E  21.4    4  121.0  ...     4     2         1.0        1.0

[28 rows x 14 columns]

# Grouping

In [154]:
cars_groups=cars.groupby(cars.gear)
cars_groups.mean()

            mpg       cyl        disp  ...      carb  light cars  Bangalore
gear                                   ...
3     15.792308  7.384615  318.576923  ...  2.615385    0.076923   0.076923
4     24.720000  4.800000  118.870000  ...  2.400000    0.800000   0.800000
5     21.380000  6.000000  202.480000  ...  4.400000    0.600000   0.400000

[3 rows x 12 columns]

In [155]:
cars_am=cars.groupby(cars.am)
cars_am.mean()

          mpg       cyl        disp  ...      carb  light cars  Bangalore
am                                   ...
0   16.153333  7.200000  298.446667  ...  2.800000    0.066667   0.066667
1   24.392308  5.076923  143.530769  ...  2.923077    0.846154   0.769231

[2 rows x 12 columns]

In [156]:
cars_groups = cars.groupby([cars.gear,cars.am])
cars_groups.mean()

               mpg       cyl        disp  ...      carb  light cars  Bangalore
gear am                                   ...
3    0   15.792308  7.384615  318.576923  ...  2.615385    0.076923   0.076923
4    0   18.500000  6.000000  167.600000  ...  4.000000    0.000000   0.000000
     1   26.275000  4.500000  106.687500  ...  2.000000    1.000000   1.000000
5    1   21.380000  6.000000  202.480000  ...  4.400000    0.600000   0.400000

[4 rows x 11 columns]

In [157]:
cars_groups.count()

         car_model  mpg  cyl  disp  hp  ...  qsec  vs  carb  light cars  Bangalore
gear am                                 ...
3    0          13   13   13    13  13  ...    13  13    13          13         13
4    0           2    2    2     2   2  ...     2   2     2           2          2
     1           8    8    8     8   8  ...     8   8     8           8          8
5    1           5    5    5     5   5  ...     5   5     5           5          5

[4 rows x 12 columns]

In [158]:
cars_groups.max()

             car_model   mpg  cyl   disp  ...  vs  carb  light cars  Bangalore
gear am                                   ...
3    0       Valiant 2  21.5    8  472.0  ...   1     4         1.0        1.0
4    0       Merc 280C  19.2    6  167.6  ...   1     4         0.0        0.0
     1      Volvo 142E  33.9    6  160.0  ...   1     4         1.0        1.0
5    1   Porsche 914-2  30.4    8  351.0  ...   1     8         1.0        1.0

[4 rows x 12 columns]

In [165]:
# groupby cylinder - How many number of cars has <=4 cylinder 
cars_groups=cars.groupby([cars.cyl])
cars_groups.count()

     car_model  mpg  disp  hp  drat  ...  am  gear  carb  light cars  Bangalore
cyl                                  ...
4            9    9     9   9     9  ...   9     9     9           9          9
6            7    7     7   7     7  ...   7     7     7           7          7
8           12   12    12  12    12  ...  12    12    12          12         12

[3 rows x 13 columns]